### ISSUE TITLE
pyo3_runtime.PanicException: Failed to import NumPy module

### ISSUE THREAD

**Issue by ShaneHarvey** [milesgranger/pyrus-cramjam#106]
When I call snappy.compress with an invalid argument cramjam displays this cryptic exception mentioning NumPy:
```python
>>> from cramjam import snappy
>>> d = snappy.compress(b'b'*1024) # bytes works fine
>>> d
cramjam.Buffer(len=70)
>>> d = snappy.compress(1) # Passing invalid argument produces cryptic error:
thread '<unnamed>' panicked at 'Failed to import NumPy module', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/numpy-0.17.2/src/npyffi/mod.rs:22:9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: Failed to import NumPy module
```

Env info:
```
$  python -m pip list
Package    Version
---------- -------
cramjam    2.6.2
pip        22.3
setuptools 65.5.0
$ python
Python 3.11.0 (main, Apr  4 2023, 20:04:59) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by milesgranger** [comment]
Ah, that's not great.
Can you try [`2.7.0rc3`](https://pypi.org/project/cramjam/2.7.0rc3/), that ought to be a better experience.

**Comment by ShaneHarvey** [comment]
yes with 2.7.0rc3 the exception is much better (only tested on macos this time):
```
>>> snappy.compress(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument 'data': failed to extract enum BytesType ('Buffer | File | pybuffer')
- variant RustyBuffer (Buffer): TypeError: failed to extract field BytesType::RustyBuffer.0, caused by TypeError: 'int' object cannot be converted to 'Buffer'
- variant RustyFile (File): TypeError: failed to extract field BytesType::RustyFile.0, caused by TypeError: 'int' object cannot be converted to 'File'
- variant PyBuffer (pybuffer): SystemError: <class 'TypeError'> returned a result with an exception set, caused by BufferError: Failed to get buffer, is it C contiguous, and shape is not null?
```
